/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TypingTutorAppGui;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Shayam
 */
public class bottom extends javax.swing.JFrame {

    /**
     * Creates new form bottom
     */
    public bottom() {
        initComponents();
        z1.setForeground(Color.BLUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        q = new javax.swing.JButton();
        w = new javax.swing.JButton();
        e = new javax.swing.JButton();
        t = new javax.swing.JButton();
        r = new javax.swing.JButton();
        y = new javax.swing.JButton();
        u = new javax.swing.JButton();
        i = new javax.swing.JButton();
        o = new javax.swing.JButton();
        a = new javax.swing.JButton();
        s = new javax.swing.JButton();
        d = new javax.swing.JButton();
        f = new javax.swing.JButton();
        h = new javax.swing.JButton();
        g = new javax.swing.JButton();
        j = new javax.swing.JButton();
        k = new javax.swing.JButton();
        l = new javax.swing.JButton();
        n = new javax.swing.JButton();
        b = new javax.swing.JButton();
        v = new javax.swing.JButton();
        x = new javax.swing.JButton();
        c = new javax.swing.JButton();
        z = new javax.swing.JButton();
        p = new javax.swing.JButton();
        m = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        btndone = new javax.swing.JButton();
        z1 = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        v1 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        n1 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        m1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("TYPE LETTERS IN BLUE COLOR");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        q.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        q.setText("Q");
        q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qActionPerformed(evt);
            }
        });

        w.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        w.setText("W");

        e.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        e.setText("E");

        t.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t.setText("T");

        r.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        r.setText("R");
        r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rActionPerformed(evt);
            }
        });

        y.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        y.setText("Y");

        u.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        u.setText("U");

        i.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        i.setText("I");

        o.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        o.setText("O");

        a.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        a.setText("A");

        s.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s.setText("S");

        d.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d.setText("D");

        f.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        f.setText("F");

        h.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        h.setText("H");

        g.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        g.setText("G");
        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });

        j.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j.setText("J");

        k.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        k.setText("K");

        l.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l.setText("L");

        n.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n.setText("N");

        b.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b.setText("B");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        v.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        v.setText("V");

        x.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        x.setText("X");

        c.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c.setText("C");

        z.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        z.setText("Z");

        p.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p.setText("P");

        m.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        m.setText("M");
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });

        Logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Logout.setText("LOGOUT");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
        });
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        btndone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndone.setText("DONE");
        btndone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndoneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndoneMouseExited(evt);
            }
        });
        btndone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoneActionPerformed(evt);
            }
        });

        z1.setBackground(new java.awt.Color(0, 0, 255));
        z1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        z1.setForeground(new java.awt.Color(204, 0, 0));
        z1.setText("Z");

        x1.setBackground(new java.awt.Color(0, 0, 255));
        x1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        x1.setForeground(new java.awt.Color(204, 0, 0));
        x1.setText("X");

        v1.setBackground(new java.awt.Color(0, 0, 255));
        v1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        v1.setForeground(new java.awt.Color(204, 0, 0));
        v1.setText("V");

        c1.setBackground(new java.awt.Color(0, 0, 255));
        c1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        c1.setForeground(new java.awt.Color(204, 0, 0));
        c1.setText("C");

        n1.setBackground(new java.awt.Color(0, 0, 255));
        n1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        n1.setForeground(new java.awt.Color(204, 0, 0));
        n1.setText("N");

        b1.setBackground(new java.awt.Color(0, 0, 255));
        b1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b1.setForeground(new java.awt.Color(204, 0, 0));
        b1.setText("B");

        m1.setBackground(new java.awt.Color(0, 0, 255));
        m1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        m1.setForeground(new java.awt.Color(204, 0, 0));
        m1.setText("M");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(z, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(k, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(q, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(i, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(o, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Logout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndone)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(z1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(c1)
                                .addGap(17, 17, 17)
                                .addComponent(v1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(n1)
                                .addGap(18, 18, 18)
                                .addComponent(m1)
                                .addGap(150, 150, 150))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(235, 235, 235))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(z1)
                    .addComponent(v1)
                    .addComponent(c1)
                    .addComponent(x1)
                    .addComponent(b1)
                    .addComponent(n1)
                    .addComponent(m1))
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q)
                    .addComponent(w)
                    .addComponent(e)
                    .addComponent(r)
                    .addComponent(t)
                    .addComponent(y)
                    .addComponent(u)
                    .addComponent(i)
                    .addComponent(o)
                    .addComponent(p))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a)
                    .addComponent(s)
                    .addComponent(d)
                    .addComponent(f)
                    .addComponent(g)
                    .addComponent(h)
                    .addComponent(j)
                    .addComponent(k)
                    .addComponent(l))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(z)
                    .addComponent(x)
                    .addComponent(c)
                    .addComponent(v)
                    .addComponent(b)
                    .addComponent(n)
                    .addComponent(m))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logout)
                    .addComponent(btndone))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        // TODO add your handling code here:
        char ch=evt.getKeyChar();
        switch(ch)
        {
            case 'a':
            a.setBackground(Color.red);
           
            break;
            case 'b':
            b.setBackground(Color.red);
            b1.setForeground(Color.red);
            n1.setForeground(Color.BLUE);
            break;
            case 'c':
            c.setBackground(Color.red);
            c1.setForeground(Color.red);
            v1.setForeground(Color.BLUE);
            break;
            case 'd':
            d.setBackground(Color.red);
            break;
            case 'e':
            e.setBackground(Color.red);
            break;
            case 'f':
            f.setBackground(Color.red);
            break;
            case 'g':
            g.setBackground(Color.red);
            break;
            case 'h':
            h.setBackground(Color.red);
            break;
            case 'i':
            i.setBackground(Color.red);
            break;
            case 'j':
            j.setBackground(Color.red);
            break;
            case 'k':
            k.setBackground(Color.red);
            break;
            case 'l':
            l.setBackground(Color.red);
            break;
            case 'm':
            m.setBackground(Color.red);
            m1.setForeground(Color.red);
            z1.setForeground(Color.BLUE);
            break;
            case 'n':
            n.setBackground(Color.red);
            n1.setForeground(Color.red);
            m1.setForeground(Color.BLUE);
            break;
            case 'o':
            o.setBackground(Color.red);
            break;
            case 'p':
            p.setBackground(Color.red);
            break;
            case 'q':
            q.setBackground(Color.red);
            break;
            case 'r':
            r.setBackground(Color.red);
            break;
            case 's':
            s.setBackground(Color.red);
            break;
            case 't':
            t.setBackground(Color.red);
            break;
            case 'u':
            u.setBackground(Color.red);
            break;
            case 'v':
            v.setBackground(Color.red);
            v1.setForeground(Color.red);
            b1.setForeground(Color.BLUE);
            break;
            case 'w':
            w.setBackground(Color.red);
            break;
            case 'x':
            x.setBackground(Color.red);
            x1.setForeground(Color.red);
            c1.setForeground(Color.BLUE);
            break;
            case 'y':
            y.setBackground(Color.red);
            break;
            case 'z':
            z.setBackground(Color.red);
            z1.setForeground(Color.red);
            x1.setForeground(Color.BLUE);
            break;
            default:
            break;

        }
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyReleased
        // TODO add your handling code here:
        char ch=evt.getKeyChar();

        switch(ch)
        {
            case 'a':
            a.setBackground(Color.white);
            break;
            case 'b':
            b.setBackground(Color.white);
            break;
            case 'c':
            c.setBackground(Color.white);
            break;
            case 'd':
            d.setBackground(Color.white);
            break;
            case 'e':
            e.setBackground(Color.white);
            break;
            case 'f':
            f.setBackground(Color.white);
            break;
            case 'g':
            g.setBackground(Color.white);
            break;
            case 'h':
            h.setBackground(Color.white);
            break;
            case 'i':
            i.setBackground(Color.white);
            break;
            case 'j':
            j.setBackground(Color.white);
            break;
            case 'k':
            k.setBackground(Color.white);
            break;
            case 'l':
            l.setBackground(Color.white);
            break;
            case 'm':
            m.setBackground(Color.white);
            break;
            case 'n':
            n.setBackground(Color.white);
            break;
            case 'o':
            o.setBackground(Color.white);
            break;
            case 'p':
            p.setBackground(Color.white);
            break;
            case 'q':
            q.setBackground(Color.white);
            break;
            case 'r':
            r.setBackground(Color.white);
            break;
            case 's':
            s.setBackground(Color.white);
            break;
            case 't':
            t.setBackground(Color.white);
            break;
            case 'u':
            u.setBackground(Color.white);
            break;
            case 'v':
            v.setBackground(Color.white);
            break;
            case 'w':
            w.setBackground(Color.white);
            break;
            case 'x':
            x.setBackground(Color.white);
            break;
            case 'y':
            y.setBackground(Color.white);
            break;
            case 'z':
            z.setBackground(Color.white);
            break;
            default:
            break;
        }
    }//GEN-LAST:event_jTextArea1KeyReleased

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        // TODO add your handling code here:
        char ch1=evt.getKeyChar();
        if(ch1!='z'&&ch1!='x'&&ch1!='c'&&ch1!='v'&&ch1!='b'&&ch1!='n'&&ch1!='m')
        {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jTextArea1KeyTyped

    private void qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qActionPerformed

    private void rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mActionPerformed

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        // TODO add your handling code here:
        Logout.setBackground(Color.red);
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        // TODO add your handling code here:
        Logout.setBackground(Color.white);
    }//GEN-LAST:event_LogoutMouseExited

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        int ans=JOptionPane.showConfirmDialog(null,"Are  You Sure","Conformation",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_LogoutActionPerformed

    private void btndoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndoneMouseEntered
        // TODO add your handling code here:
        btndone.setBackground(Color.red);
    }//GEN-LAST:event_btndoneMouseEntered

    private void btndoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndoneMouseExited
        // TODO add your handling code here:
        btndone.setBackground(Color.white);
    }//GEN-LAST:event_btndoneMouseExited

    private void btndoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoneActionPerformed
        // TODO add your handling code here:
        speedandaccuracy saa=new speedandaccuracy();
        saa.setVisible(true);
        this .dispose();
    }//GEN-LAST:event_btndoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bottom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bottom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bottom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bottom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bottom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton a;
    private javax.swing.JButton b;
    private javax.swing.JLabel b1;
    private javax.swing.JButton btndone;
    private javax.swing.JButton c;
    private javax.swing.JLabel c1;
    private javax.swing.JButton d;
    private javax.swing.JButton e;
    private javax.swing.JButton f;
    private javax.swing.JButton g;
    private javax.swing.JButton h;
    private javax.swing.JButton i;
    private javax.swing.JButton j;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton k;
    private javax.swing.JButton l;
    private javax.swing.JButton m;
    private javax.swing.JLabel m1;
    private javax.swing.JButton n;
    private javax.swing.JLabel n1;
    private javax.swing.JButton o;
    private javax.swing.JButton p;
    private javax.swing.JButton q;
    private javax.swing.JButton r;
    private javax.swing.JButton s;
    private javax.swing.JButton t;
    private javax.swing.JButton u;
    private javax.swing.JButton v;
    private javax.swing.JLabel v1;
    private javax.swing.JButton w;
    private javax.swing.JButton x;
    private javax.swing.JLabel x1;
    private javax.swing.JButton y;
    private javax.swing.JButton z;
    private javax.swing.JLabel z1;
    // End of variables declaration//GEN-END:variables
}
