

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TypingTutorAppGui;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Shayam
 */
public class UserChoice extends javax.swing.JFrame {

    /**
     * Creates new form UserChoice
     */
    public UserChoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jrparagraph = new javax.swing.JRadioButton();
        jrmiddle = new javax.swing.JRadioButton();
        jrbottom = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();
        jrscore = new javax.swing.JRadioButton();
        jrtop = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        back = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jrparagraph.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrparagraph);
        jrparagraph.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrparagraph.setForeground(new java.awt.Color(240, 240, 240));
        jrparagraph.setText("DRILL WITH PARAGRAPH");
        jrparagraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrparagraphjrbAddEmpActionPerformed(evt);
            }
        });

        jrmiddle.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrmiddle);
        jrmiddle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrmiddle.setForeground(new java.awt.Color(240, 240, 240));
        jrmiddle.setText("DRILL WITH MIDDLE ROW");
        jrmiddle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrmiddlejrbSearchEmpActionPerformed(evt);
            }
        });

        jrbottom.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbottom);
        jrbottom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbottom.setForeground(new java.awt.Color(240, 240, 240));
        jrbottom.setText("DRILL WITH   BOTTOM ROW");
        jrbottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbottomjrbShowAllEmpActionPerformed(evt);
            }
        });

        btnDoTask.setBackground(new java.awt.Color(0, 0, 0));
        btnDoTask.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(240, 240, 240));
        btnDoTask.setText("Do Task");
        btnDoTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDoTaskMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDoTaskMouseExited(evt);
            }
        });
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskbtnDoTaskActionPerformed(evt);
            }
        });

        jrscore.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrscore);
        jrscore.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrscore.setForeground(new java.awt.Color(240, 240, 240));
        jrscore.setText("SEE SCORE");

        jrtop.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrtop);
        jrtop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrtop.setForeground(new java.awt.Color(240, 240, 240));
        jrtop.setText("DRILL WITH TOP ROW");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("ENTER YOUR CHOICE");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("TYPING TUTOR APP");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TypingTutorAppGui/admin (2).png"))); // NOI18N
        jLabel7.setText("jLabel7");

        Logout.setBackground(new java.awt.Color(0, 0, 0));
        Logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(240, 240, 240));
        Logout.setText("LOGOUT");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
        });
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(240, 240, 240));
        back.setText("BACK");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(Logout)
                            .addGap(119, 119, 119)
                            .addComponent(btnDoTask)
                            .addGap(24, 24, 24))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(244, 244, 244)))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jrtop)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jrmiddle)
                                            .addComponent(jrparagraph, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(56, 56, 56))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jrscore)
                                    .addContainerGap()))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jrbottom, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jrparagraph)
                        .addGap(18, 18, 18)
                        .addComponent(jrmiddle)
                        .addGap(18, 18, 18)
                        .addComponent(jrtop)
                        .addGap(18, 18, 18)
                        .addComponent(jrbottom)
                        .addGap(18, 18, 18)
                        .addComponent(jrscore)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Logout)
                            .addComponent(btnDoTask))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrparagraphjrbAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrparagraphjrbAddEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrparagraphjrbAddEmpActionPerformed

    private void jrmiddlejrbSearchEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrmiddlejrbSearchEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrmiddlejrbSearchEmpActionPerformed

    private void jrbottomjrbShowAllEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbottomjrbShowAllEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbottomjrbShowAllEmpActionPerformed

    private void btnDoTaskbtnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskbtnDoTaskActionPerformed
        // TODO add your handling code here:
        if(jrparagraph.isSelected())
        {
            paragraph pg=new paragraph();
            pg.setVisible(true);
            this.dispose();
        }
        else if(jrmiddle.isSelected())
        {
             middle md=new middle();
            md.setVisible(true);
            this.dispose();
        }
         else if(jrtop.isSelected())
         {
             top tp=new top();
            tp.setVisible(true);
            this.dispose();
         }
         else if(jrbottom.isSelected())
         {
             bottom bt=new bottom();
           bt.setVisible(true);
            this.dispose();
         }
         else if(jrscore.isSelected())
         {
              score sc=new score();
            sc.setVisible(true);
            this.dispose();
         }
        else
         {
              JOptionPane.showMessageDialog(null,"SELECT CHOICE FIRST", "Error", JOptionPane.ERROR_MESSAGE);
         
         }
    }//GEN-LAST:event_btnDoTaskbtnDoTaskActionPerformed

    private void btnDoTaskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoTaskMouseEntered
        // TODO add your handling code here:
         btnDoTask.setBackground(Color.red);
    }//GEN-LAST:event_btnDoTaskMouseEntered

    private void btnDoTaskMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoTaskMouseExited
        // TODO add your handling code here:
        btnDoTask.setBackground(Color.black);
    }//GEN-LAST:event_btnDoTaskMouseExited

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        // TODO add your handling code here:
        Logout.setBackground(Color.red);
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        // TODO add your handling code here:
        Logout.setBackground(Color.black);
    }//GEN-LAST:event_LogoutMouseExited

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        int ans=JOptionPane.showConfirmDialog(null,"Are  You Sure","Conformation",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        System.exit(0);

    }//GEN-LAST:event_LogoutActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        AppLogin applogin=new AppLogin();
        applogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        back.setBackground(Color.red);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        back.setBackground(Color.black);
    }//GEN-LAST:event_backMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserChoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton back;
    private javax.swing.JButton btnDoTask;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jrbottom;
    private javax.swing.JRadioButton jrmiddle;
    private javax.swing.JRadioButton jrparagraph;
    private javax.swing.JRadioButton jrscore;
    private javax.swing.JRadioButton jrtop;
    // End of variables declaration//GEN-END:variables
}
